version: 2

jobs:

  build-python35:
    docker:
      - image: python:3.5.3
    steps:
      - checkout
      - run: make deps deps-test install test

  build-python36:
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run: make deps deps-test install test

workflows:
  version: 2
  build:
    jobs:
      - build-python35
      - build-python36
