version: 2

jobs:

  build-python36:
    docker:
      - image: python:3.6.15-buster
    steps:
      - checkout
      # workaround for OCR-D/core#923
      - run: apt-get update && apt-get install -y libgeos-dev
      - run: make deps-ubuntu deps-test deps install
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

  build-python37:
    docker:
      - image: python:3.7.15-buster
    steps:
      - checkout
      - run: make deps-ubuntu deps-test deps install
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

  build-python38:
    docker:
      - image: python:3.8.14-buster
    steps:
      - checkout
      - run: make deps-ubuntu deps-test deps install
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

  build-python39:
    docker:
      - image: python:3.9.14-buster
    steps:
      - checkout
      - run: make deps-ubuntu deps-test deps install
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build-python36
      - build-python37
      - build-python38
      - build-python39
