version: 2

jobs:

  build-python36:
    docker:
      - image: python:3.6.12-buster
    steps:
      - checkout
      - run: make deps-ubuntu deps-test deps install assets
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

  build-python37:
    docker:
      - image: python:3.7.9-buster
    steps:
      - checkout
      - run: make deps-ubuntu deps-test deps install assets
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

  build-python38:
    docker:
      - image: python:3.8.5-buster
    steps:
      - checkout
      - run: make deps-ubuntu deps-test deps install assets
      - run: ocrd resmgr download ocrd-kraken-segment blla.mlmodel
      - run: ocrd resmgr download ocrd-kraken-recognize en_best.mlmodel
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build-python36
      - build-python37
      - build-python38
